### ISSUE TITLE
Question regarding db-name

### ISSUE THREAD

**Issue by abuisman** [nickcharlton/heroku-postgres#1]
When creating the `db` object I need to use the `app-name` and `db-name`. What does this `db-name` look like? Should it be the `ENV` style string that heroku assigns such as 'HEROKU_POSTGRES_SOME-MYTHICAL-ANIMAL` or should it be the postrgres database name that looks like a random string such as 'hai123h12i12i33'?

Also, when I do db.capture_backup(true) the backup just hangs without me being able to see if anything is actually being done. Is there a way to check if a backup is running? Perhaps through the heroku-toolbelt in the cli?

**Comment by nickcharlton** [comment]
1. It's the `ENV` style database name that Heroku provides.
2. The blocking is something I wanted to improve, but there's not much I could figure out. It does allow you to provide a block, but you can't see how long is left or anything like that.

Also; keep raising things. I'll have a look at clarifying some of the docs and so forth. If you don't understand something, the client is bad.
